name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Se ejecuta todos los días a medianoche
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "repositories"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
